name: onyx_b2g_config
on: 
  workflow_dispatch:

# NEED  
# 1. secrets.GIT_ACCESS_TOKEN
# 2. secrets.RCLONE
# 3. device_name eg；onyx(oneplus x), bacon(oneplus one), phhgsi_arm64_a(phh's gsi) etc.
#     out/device_name
# 4. build_device_tag: eg: full-onyx-eng, full-bacon-userdebug etc.
#    gsi-build.sh build_device_tag
# 5. repo_dispatches: https://api.github.com/repos/(you id)/(you repo name)/dispatches
# 6. b2g_source: 
#         remote soucre address
# for example:
env:
  GIT_ACCESS_TOKEN: ${{secrets.GIT_ACCESS_TOKEN}}
  device_name: onyx
  repo_dispatches: "https://api.github.com/repos/b2g-gsi/build-actions/dispatches"
  b2g_source: "https://github.com/b2gos/B2G"
  b2g_branch: "gsi"
  build_device_tag: onyx
  device_arch: armv7-linux-androideabi
  actions_branch: b2g_gsi

jobs: 
  config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Action        
      run: |
        ./onyx/init/webhook.sh onyx_gecko_build
        #onyx_b2g_repack onyx_aosp_build onyx_gecko_build onyx_b2g_build onyx_api_daemon_build
